<a href="https://colab.research.google.com/github/hsmu-jeongeun/machine-learning-practice/blob/main/250416_cross_validation_hyperparameter_tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 교차 검증과 그리드 서치

## 검증 데이터셋

In [6]:
import pandas as pd

wine = pd.read_csv('https://bit.ly/wine-date')

### 문제 1 : wine 데이터 확인

In [7]:
# wine 처음 5개 행 데이터 확인
wine.head()

   alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [8]:
# wine 전체 행의 개수 확인
print(wine.shape[0])

6497

In [9]:
# wine 데이터 통계값 확인 (각 특성별 평균, 표준편차, 최소값, 최대값 등)
wine.describe()

           alcohol        sugar           pH        class
count  6497.000000  6497.000000  6497.000000  6497.000000
mean     10.491801     5.443235     3.218501     0.753886
std       1.192712     4.757804     0.160787     0.430779
min       8.000000     0.600000     2.720000     0.000000
25%       9.500000     1.800000     3.110000     1.000000
50%      10.300000     3.000000     3.210000     1.000000
75%      11.300000     8.100000     3.320000     1.000000
max      14.900000    65.800000     4.010000     1.000000

In [10]:
# 화이트 와인, 레드 와인 데이터 개수 확인
wine['class'].value_counts()

class
1.0    4898
0.0    1599
Name: count, dtype: int64

### 데이터셋 분류

In [11]:
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

In [13]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 4.7 MB/s  0:00:01 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 4.7 MB/s  0:00:04 eta 0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [14]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size=0.2, random_state=42)

In [15]:
sub_input, val_input, sub_target, val_target = train_test_split(
    train_input, train_target, test_size=0.2, random_state=42)

In [16]:
print(sub_input.shape, val_input.shape)

(4157, 3) (1040, 3)

In [17]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)

print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077

## 교차 검증

In [18]:
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target)
print(scores)

{'fit_time': array([0.00652981, 0.00574589, 0.00528526, 0.00459504, 0.00399303]), 'score_time': array([0.00074887, 0.00092316, 0.000458  , 0.00030208, 0.00026798]), 'test_score': array([0.87019231, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}

In [19]:
import numpy as np

print(np.mean(scores['test_score']))

0.8554925223957948

In [20]:
from sklearn.model_selection import StratifiedKFold

scores = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
print(np.mean(scores['test_score']))

0.8554925223957948

In [21]:
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_validate(dt, train_input, train_target, cv=splitter)
print(np.mean(scores['test_score']))

0.8581873425226026

## 하이퍼파라미터 튜닝

In [22]:
from sklearn.model_selection import GridSearchCV

params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

In [23]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)

In [24]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [25]:
dt = gs.best_estimator_
print(dt.score(train_input, train_target))

0.9615162593804117

In [26]:
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}

In [27]:
print(gs.cv_results_['mean_test_score'])

[0.86800067 0.86453617 0.86492226 0.86780891 0.86761605]

In [28]:
best_index = np.argmax(gs.cv_results_['mean_test_score'])
print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}

In [29]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
          'max_depth': range(5, 20, 1),
          'min_samples_split': range(2, 100, 10)
          }

In [30]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [31]:
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': np.float64(0.0004), 'min_samples_split': 12}

In [32]:
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731

In [33]:
# 교차검증 수행 시간 프린트
gs.cv_results_['mean_fit_time']

array([0.00313916, 0.00291414, 0.00267   , ..., 0.00244946, 0.00181198,
       0.00211587], shape=(1350,))

### 랜덤 서치

In [34]:
from scipy.stats import uniform, randint

In [35]:
# 균등 분포 샘플링
rgen = randint(0, 10)
rgen.rvs(10)

array([2, 3, 3, 9, 5, 0, 5, 5, 7, 6])

In [36]:
np.unique(rgen.rvs(1000), return_counts=True) # 빈도도 함께 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 89, 111,  97, 104,  92,  90, 100, 105, 101, 111]))

In [37]:
ugen = uniform(0, 1)
ugen.rvs(10)

array([0.77215154, 0.63390418, 0.4718185 , 0.72198902, 0.65790702,
       0.80405929, 0.79161941, 0.78704801, 0.51694298, 0.80886247])

In [38]:
params = {'min_impurity_decrease': uniform(0.0001, 0.001),
          'max_depth': randint(20, 50),
          'min_samples_split': randint(2, 25),
          'min_samples_leaf': randint(1, 25),
          }

In [39]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params,
                        n_iter=100, n_jobs=-1, random_state=42)
rs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d3cae90>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x11d3cac10>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d401ba0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d3cbb10>},
                   random_state=42)

In [40]:
print(rs.best_params_)

{'max_depth': 39, 'min_impurity_decrease': np.float64(0.00034102546602601173), 'min_samples_leaf': 7, 'min_samples_split': 13}

In [41]:
print(np.max(rs.cv_results_['mean_test_score']))

0.8695428296438884

In [42]:
dt = rs.best_estimator_

print(dt.score(test_input, test_target))

0.86

In [43]:
rs.cv_results_['mean_fit_time']

array([0.00325842, 0.002918  , 0.0029635 , 0.00307627, 0.00246181,
       0.00272536, 0.00258021, 0.00245519, 0.00238466, 0.0027441 ,
       0.00224957, 0.00262904, 0.00257883, 0.00253067, 0.00242648,
       0.0023942 , 0.00260692, 0.0021914 , 0.00218253, 0.00230999,
       0.0027236 , 0.00218639, 0.00236697, 0.00205617, 0.00230894,
       0.00260787, 0.00233703, 0.00267053, 0.00204482, 0.0022645 ,
       0.00194392, 0.00269475, 0.00191011, 0.00242329, 0.00265508,
       0.00248404, 0.00267959, 0.00243506, 0.00273929, 0.00235648,
       0.00247355, 0.0025146 , 0.00267773, 0.00217409, 0.00223351,
       0.00227599, 0.0020277 , 0.00251551, 0.00238647, 0.00308437,
       0.0025444 , 0.00262861, 0.00251145, 0.00180163, 0.00215001,
       0.00271535, 0.00222635, 0.00213194, 0.00226336, 0.00306935,
       0.00330739, 0.00185914, 0.00225062, 0.00261045, 0.00217352,
       0.00179005, 0.00228162, 0.00279098, 0.00231586, 0.00286946,
       0.00231061, 0.00309753, 0.00237107, 0.00210872, 0.00245795,
       0.00310812, 0.00204444, 0.00317521, 0.00196791, 0.00183291,
       0.00262532, 0.00253778, 0.00263896, 0.00175419, 0.00184579,
       0.00221453, 0.00243168, 0.00318737, 0.00377221, 0.00266161,
       0.00194945, 0.00231066, 0.0030829 , 0.00262556, 0.0029243 ,
       0.00302563, 0.00270123, 0.0024837 , 0.00386834, 0.00352707])

In [44]:
print(np.mean(rs.cv_results_['mean_fit_time']))

0.0025085339546203618

### 결정트리 분할 옵션 변경

In [45]:
rs2 = RandomizedSearchCV(DecisionTreeClassifier(splitter='random', random_state=42), params,
                        n_iter=100, n_jobs=-1, random_state=42)
rs2.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42,
                                                    splitter='random'),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d3cae90>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x11d3cac10>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d401ba0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x11d3cbb10>},
                   random_state=42)

In [46]:
print(rs2.best_params_)
print(np.max(rs2.cv_results_['mean_test_score']))

dt = rs2.best_estimator_
print(dt.score(test_input, test_target))

{'max_depth': 43, 'min_impurity_decrease': np.float64(0.00011407982271508446), 'min_samples_leaf': 19, 'min_samples_split': 18}
0.8458726956392981
0.786923076923077

In [47]:
rs2.cv_results_['mean_fit_time']

array([0.00133929, 0.00142646, 0.00113082, 0.00100393, 0.0008338 ,
       0.00095673, 0.00090694, 0.00080981, 0.00122824, 0.00099502,
       0.00090866, 0.00073743, 0.00080781, 0.00076613, 0.00072818,
       0.00074363, 0.00072317, 0.00093784, 0.00091848, 0.00107822,
       0.00081992, 0.00072885, 0.00094061, 0.00082612, 0.00077696,
       0.00078506, 0.0006568 , 0.00068798, 0.00063562, 0.00107117,
       0.00104475, 0.00080662, 0.00057282, 0.00078411, 0.00085263,
       0.00079165, 0.00073457, 0.00110178, 0.00065427, 0.00092196,
       0.00073318, 0.00087442, 0.00080338, 0.00061741, 0.00116711,
       0.00105963, 0.00107317, 0.00078158, 0.00068564, 0.00075083,
       0.00095501, 0.00088224, 0.00067635, 0.00077968, 0.00115962,
       0.00076509, 0.00072036, 0.00064197, 0.00098991, 0.00066199,
       0.00096297, 0.00056472, 0.00101252, 0.00086026, 0.00096612,
       0.00067248, 0.00083752, 0.00065241, 0.00077586, 0.00079799,
       0.00095563, 0.00085878, 0.000771  , 0.00113401, 0.00067677,
       0.0006392 , 0.00068541, 0.00106449, 0.00064678, 0.00111794,
       0.00121036, 0.00070682, 0.0011775 , 0.00059214, 0.00113063,
       0.00098157, 0.00118656, 0.00092521, 0.00082555, 0.00067649,
       0.00062304, 0.00105448, 0.0011888 , 0.0010262 , 0.00105782,
       0.00078335, 0.00061183, 0.00063186, 0.00069313, 0.0007762 ])

In [48]:
print(np.mean(rs2.cv_results_['mean_fit_time']))

0.0008646578788757324

## 문제 2: 위 코드가 기존 랜덤 서치 코드와 다른 점을 2가지 적어보세요. 

### 1. 그리드 서치는 모든 조합을 시도하지만 랜덤 서치는 지정된 횟수만큼 무작위로 조합을 시도함.
### 2. 그리드 서치는 랜덤 서치 코드와 다르게 같은 입력이면 항상 같은 결과를 도출함.

In [50]:
%pip install cv2
%pip install sys

ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement sys (from versions: none)
ERROR: No matching distribution found for sys
Note: you may need to restart the kernel to use updated packages.

In [51]:
import cv2 as cv
import sys

img = cv.imread('girl_laughing.jpg')

if img is None:
    sys.exit("Could not read the image.")
    
cv.imshow('Display window', img)

cv.waitKey()
cv.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'